(ns aether.vfs.compose
  "Composes data roots. The base game contents are served read-only by a
  read-only Provider (any read-only Provider slots into these seams). Runtime
  writes (saves, INI tweaks, mod-manager drops) must never touch the base —
  they land in a writable OVERRIDES host directory via OverlayProvider, which
  also copies-up any base file modified in place."
  (:require [aether.vfs.providers.layered :as layered]
            [aether.vfs.providers.overlay :as overlay]))

(defn build-data-root
  "Overlay(overrides-dir) > snapshot: base reads pass through; writes and new
  files land in overrides-dir."
  [snapshot overrides-dir]
  (overlay/overlay-provider snapshot overrides-dir))

(defn build-data-root-over
  "Overlay(overrides-dir) > Layered(top = snapshot mods, bottom = base): the
  snapshot's mod files shadow same-path base files; base files the mods don't
  touch pass through; user edits/new files land in overrides-dir."
  [snapshot base overrides-dir]
  (overlay/overlay-provider (layered/layered-provider snapshot base) overrides-dir))

(defn build-inline-root
  "Overlay(overrides-dir) > Inline(files): the inline files (generated bytes,
  RAM-only) are served read-only; game writes and new files land in
  overrides-dir. Nothing touches a store/cache."
  [inline overrides-dir]
  (overlay/overlay-provider inline overrides-dir))
