[package]
name = "vfs-zip"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
vfs-core.workspace = true
vfs-provider.workspace = true

[dev-dependencies]
vfs-testkit.workspace = true
vfs-provider = { workspace = true, features = ["conformance"] }
tempfile.workspace = true

[lints]
workspace = true
