[package]
name = "vfs-shim-dll"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
vfs-env.workspace = true
vfs-shim.workspace = true
windows-sys = { workspace = true, features = ["Win32_Foundation"] }

[lints]
workspace = true
